# PowerShell script to set up stewardPOS in Docker Desktop
# Run this script from the project root directory

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "stewardPOS Docker Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if Docker is running
Write-Host "Checking Docker Desktop..." -ForegroundColor Yellow
try {
    docker ps | Out-Null
    Write-Host "✅ Docker Desktop is running" -ForegroundColor Green
} catch {
    Write-Host "❌ Docker Desktop is not running!" -ForegroundColor Red
    Write-Host "Please start Docker Desktop and try again." -ForegroundColor Yellow
    exit 1
}

# Check if .env file exists
Write-Host ""
Write-Host "Checking environment file..." -ForegroundColor Yellow
if (Test-Path ".env") {
    Write-Host "✅ .env file exists" -ForegroundColor Green
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Keeping existing .env file" -ForegroundColor Yellow
        $createEnv = $false
    } else {
        $createEnv = $true
    }
} else {
    Write-Host "⚠️  .env file not found" -ForegroundColor Yellow
    $createEnv = $true
}

# Create .env file if needed
if ($createEnv) {
    Write-Host ""
    Write-Host "Creating .env file..." -ForegroundColor Yellow
    
    # Generate a secure JWT secret
    $jwtSecret = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 32 | ForEach-Object {[char]$_})
    
    $envContent = @"
# =============================================================================
# Docker Compose Environment Variables
# =============================================================================
# Generated by setup-docker.ps1

# PostgreSQL Database Configuration
POSTGRES_DB=stewardpos
POSTGRES_USER=stewardpos_user
POSTGRES_PASSWORD=stewardpos_secure_password_123

# MinIO Storage Configuration
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin123

# Backend Database Configuration
DB_NAME=stewardpos
DB_USER=stewardpos_user
DB_PASSWORD=stewardpos_secure_password_123

# Backend JWT Configuration
JWT_SECRET=$jwtSecret
JWT_EXPIRES_IN=7d

# Backend CORS Configuration
CORS_ORIGIN=http://localhost:8080,http://localhost:3001

# Backend Port
BACKEND_PORT=3001

# Frontend API Configuration
VITE_API_BASE_URL=http://localhost:3001

# Auto-seed database on first startup
AUTO_SEED=true
"@
    
    $envContent | Out-File -FilePath ".env" -Encoding utf8
    Write-Host "✅ .env file created" -ForegroundColor Green
    Write-Host "⚠️  IMPORTANT: Change passwords in .env before production use!" -ForegroundColor Yellow
}

# Build Docker images
Write-Host ""
Write-Host "Building Docker images..." -ForegroundColor Yellow
Write-Host "This may take several minutes on first run..." -ForegroundColor Gray
docker-compose build

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Docker build failed!" -ForegroundColor Red
    exit 1
}

Write-Host "✅ Docker images built successfully" -ForegroundColor Green

# Start services
Write-Host ""
Write-Host "Starting Docker services..." -ForegroundColor Yellow
docker-compose up -d

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Failed to start services!" -ForegroundColor Red
    exit 1
}

# Wait for services to be healthy
Write-Host ""
Write-Host "Waiting for services to be ready..." -ForegroundColor Yellow
Start-Sleep -Seconds 10

# Check service status
Write-Host ""
Write-Host "Service Status:" -ForegroundColor Cyan
docker-compose ps

# Test backend health
Write-Host ""
Write-Host "Testing backend health..." -ForegroundColor Yellow
Start-Sleep -Seconds 5

$maxRetries = 30
$retryCount = 0
$backendHealthy = $false

while ($retryCount -lt $maxRetries -and -not $backendHealthy) {
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:3001/api/health" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200) {
            $backendHealthy = $true
            Write-Host "✅ Backend is healthy" -ForegroundColor Green
        }
    } catch {
        $retryCount++
        Write-Host "⏳ Waiting for backend... ($retryCount/$maxRetries)" -ForegroundColor Gray
        Start-Sleep -Seconds 2
    }
}

if (-not $backendHealthy) {
    Write-Host "⚠️  Backend health check timed out" -ForegroundColor Yellow
    Write-Host "Check logs with: docker-compose logs backend" -ForegroundColor Yellow
}

# Final instructions
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Access the application:" -ForegroundColor Yellow
Write-Host "  Frontend:  http://localhost:8080" -ForegroundColor White
Write-Host "  Backend:   http://localhost:3001" -ForegroundColor White
Write-Host "  MinIO:     http://localhost:9001" -ForegroundColor White
Write-Host ""
Write-Host "Default admin credentials:" -ForegroundColor Yellow
Write-Host "  Email:    admin@demo.local" -ForegroundColor White
Write-Host "  Password: DemoPass!1" -ForegroundColor White
Write-Host ""
Write-Host "Useful commands:" -ForegroundColor Yellow
Write-Host "  View logs:    docker-compose logs -f" -ForegroundColor White
Write-Host "  Stop:         docker-compose down" -ForegroundColor White
Write-Host "  Restart:      docker-compose restart" -ForegroundColor White
Write-Host "  Status:       docker-compose ps" -ForegroundColor White
Write-Host ""

