#!/bin/bash
# Bash script to set up stewardPOS in Docker Desktop
# Run this script from the project root directory

set -e

echo "========================================"
echo "stewardPOS Docker Setup"
echo "========================================"
echo ""

# Check if Docker is running
echo "Checking Docker Desktop..."
if docker ps > /dev/null 2>&1; then
    echo "✅ Docker Desktop is running"
else
    echo "❌ Docker Desktop is not running!"
    echo "Please start Docker Desktop and try again."
    exit 1
fi

# Check if .env file exists
echo ""
echo "Checking environment file..."
if [ -f ".env" ]; then
    echo "✅ .env file exists"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Keeping existing .env file"
        CREATE_ENV=false
    else
        CREATE_ENV=true
    fi
else
    echo "⚠️  .env file not found"
    CREATE_ENV=true
fi

# Create .env file if needed
if [ "$CREATE_ENV" = true ]; then
    echo ""
    echo "Creating .env file..."
    
    # Generate a secure JWT secret
    JWT_SECRET=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
    
    cat > .env << EOF
# =============================================================================
# Docker Compose Environment Variables
# =============================================================================
# Generated by setup-docker.sh

# PostgreSQL Database Configuration
POSTGRES_DB=stewardpos
POSTGRES_USER=stewardpos_user
POSTGRES_PASSWORD=stewardpos_secure_password_123

# MinIO Storage Configuration
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin123

# Backend Database Configuration
DB_NAME=stewardpos
DB_USER=stewardpos_user
DB_PASSWORD=stewardpos_secure_password_123

# Backend JWT Configuration
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d

# Backend CORS Configuration
CORS_ORIGIN=http://localhost:8080,http://localhost:3001

# Backend Port
BACKEND_PORT=3001

# Frontend API Configuration
VITE_API_BASE_URL=http://localhost:3001

# Auto-seed database on first startup
AUTO_SEED=true
EOF
    
    echo "✅ .env file created"
    echo "⚠️  IMPORTANT: Change passwords in .env before production use!"
fi

# Build Docker images
echo ""
echo "Building Docker images..."
echo "This may take several minutes on first run..."
docker-compose build

if [ $? -ne 0 ]; then
    echo "❌ Docker build failed!"
    exit 1
fi

echo "✅ Docker images built successfully"

# Start services
echo ""
echo "Starting Docker services..."
docker-compose up -d

if [ $? -ne 0 ]; then
    echo "❌ Failed to start services!"
    exit 1
fi

# Wait for services to be healthy
echo ""
echo "Waiting for services to be ready..."
sleep 10

# Check service status
echo ""
echo "Service Status:"
docker-compose ps

# Test backend health
echo ""
echo "Testing backend health..."
sleep 5

MAX_RETRIES=30
RETRY_COUNT=0
BACKEND_HEALTHY=false

while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$BACKEND_HEALTHY" = false ]; do
    if curl -f http://localhost:3001/api/health > /dev/null 2>&1; then
        BACKEND_HEALTHY=true
        echo "✅ Backend is healthy"
    else
        RETRY_COUNT=$((RETRY_COUNT + 1))
        echo "⏳ Waiting for backend... ($RETRY_COUNT/$MAX_RETRIES)"
        sleep 2
    fi
done

if [ "$BACKEND_HEALTHY" = false ]; then
    echo "⚠️  Backend health check timed out"
    echo "Check logs with: docker-compose logs backend"
fi

# Final instructions
echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Access the application:"
echo "  Frontend:  http://localhost:8080"
echo "  Backend:   http://localhost:3001"
echo "  MinIO:     http://localhost:9001"
echo ""
echo "Default admin credentials:"
echo "  Email:    admin@demo.local"
echo "  Password: DemoPass!1"
echo ""
echo "Useful commands:"
echo "  View logs:    docker-compose logs -f"
echo "  Stop:         docker-compose down"
echo "  Restart:      docker-compose restart"
echo "  Status:       docker-compose ps"
echo ""

