import crypto from 'crypto';
import logger from '../utils/logger';

/**
 * Encrypting the payment credentials we hold on someone else's behalf.
 *
 * A shop's Stripe key lives in `settings.config.terminalCredentials`, and until
 * now it lived there in plain text. On a self-hosted install that is the
 * operator's own key in their own database — poor practice, their risk. On a
 * VPS we run for them it is *their* live key in *our* database, and one leaked
 * backup is a full account takeover for every tenant at once: a live key can
 * charge cards, refund to destinations of the holder's choosing, read customer
 * records and change where payouts land.
 *
 * So the ciphertext and the key are kept apart. The key comes from the
 * environment and never from the database, which means a dump of the database
 * alone — the ordinary way this leaks — is not enough to use what is in it.
 *
 * AES-256-GCM rather than CBC: it authenticates as well as encrypts, so a
 * tampered value fails to decrypt instead of quietly yielding different bytes.
 */

/** Marks a value this module produced, so plaintext left over from before is recognisable. */
const PREFIX = 'enc:v1:';

/**
 * A fixed salt for deriving the encryption key from `CREDENTIALS_KEY`.
 *
 * A per-value salt is what you want when the input is a human-chosen password
 * and an attacker can precompute against many of them. Here the input is one
 * high-entropy value per install, generated by the operator with
 * `openssl rand -base64 32` as the install guide instructs — there is nothing
 * to precompute across and no user-chosen weakness to stretch away from.
 *
 * The derivation exists so any string works as the environment variable, rather
 * than requiring the operator to supply exactly 32 raw bytes and getting a
 * confusing failure when they do not.
 */
const SALT = Buffer.from('stewardpos.credentials.v1');

/** Derived once: scrypt is deliberately slow, and this runs on every card charge. */
let cachedKey: Buffer | null = null;
let cachedFrom: string | null = null;

function encryptionKey(): Buffer | null {
  const secret = process.env.CREDENTIALS_KEY;
  if (!secret) return null;

  if (cachedKey && cachedFrom === secret) return cachedKey;

  cachedKey = crypto.scryptSync(secret, SALT, 32);
  cachedFrom = secret;
  return cachedKey;
}

/** Whether this install is holding its payment credentials encrypted. */
export function encryptionAvailable(): boolean {
  return encryptionKey() !== null;
}

export function isEncrypted(value: unknown): boolean {
  return typeof value === 'string' && value.startsWith(PREFIX);
}

/**
 * Encrypt one secret for storage.
 *
 * Returns the value unchanged when no key is configured. That is deliberate: an
 * install that has not set `CREDENTIALS_KEY` should keep working exactly as it
 * did rather than lose the ability to save its own settings, and the startup
 * warning is what tells the operator to fix it. Refusing here would turn a
 * security improvement into an outage on upgrade.
 */
export function encryptSecret(value: string): string {
  const key = encryptionKey();
  if (!key || !value) return value;
  if (isEncrypted(value)) return value;

  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();

  return `${PREFIX}${iv.toString('base64')}:${tag.toString('base64')}:${ciphertext.toString('base64')}`;
}

/**
 * Decrypt one stored secret.
 *
 * A value with no marker is returned as-is: that is either a credential saved
 * before this existed, or an install with no key configured. Both must keep
 * working, or enabling encryption would take card payments offline for everyone
 * who had already saved a key.
 */
export function decryptSecret(stored: string): string {
  if (!isEncrypted(stored)) return stored;

  const key = encryptionKey();
  if (!key) {
    // Encrypted data and no key to open it. Almost always a `CREDENTIALS_KEY`
    // that was set and then lost or changed — worth saying plainly, because the
    // symptom otherwise is card payments failing for no visible reason.
    throw new Error(
      'A payment credential is encrypted but CREDENTIALS_KEY is not set. ' +
        'Restore the original key, or re-enter the payment credentials in Settings.'
    );
  }

  const [, , iv, tag, ciphertext] = stored.split(':');
  try {
    const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(iv, 'base64'));
    decipher.setAuthTag(Buffer.from(tag, 'base64'));
    return Buffer.concat([
      decipher.update(Buffer.from(ciphertext, 'base64')),
      decipher.final(),
    ]).toString('utf8');
  } catch {
    // Wrong key, or tampered ciphertext — GCM cannot tell them apart, and the
    // remedy is the same either way.
    throw new Error(
      'A payment credential could not be decrypted. CREDENTIALS_KEY may have changed ' +
        'since it was saved; re-enter the payment credentials in Settings.'
    );
  }
}

type Credentials = Record<string, unknown>;

/** Encrypt every secret in a credentials bag, leaving non-strings alone. */
export function encryptCredentials(credentials: Credentials): Credentials {
  const out: Credentials = {};
  for (const [name, value] of Object.entries(credentials)) {
    out[name] = typeof value === 'string' && value ? encryptSecret(value) : value;
  }
  return out;
}

export function decryptCredentials(credentials: Credentials): Credentials {
  const out: Credentials = {};
  for (const [name, value] of Object.entries(credentials)) {
    out[name] = typeof value === 'string' && value ? decryptSecret(value) : value;
  }
  return out;
}

/**
 * Say something when live keys are sitting in the clear.
 *
 * Called once at startup rather than on every read: a warning on every card
 * charge is one nobody sees, and this is a condition of the install rather than
 * of any particular request.
 */
export function warnIfCredentialsUnprotected(credentials: Credentials | null | undefined): void {
  if (!credentials) return;

  const stored = Object.values(credentials).filter((value) => typeof value === 'string' && value);
  if (stored.length === 0) return;

  const plaintext = stored.filter((value) => !isEncrypted(value));
  if (plaintext.length === 0) return;

  if (!encryptionAvailable()) {
    logger.error(
      `${plaintext.length} payment credential(s) are stored in plain text and CREDENTIALS_KEY is not set. ` +
        'Anyone who can read this database, or a backup of it, can use them. ' +
        'Generate a key with: openssl rand -base64 32'
    );
    return;
  }

  logger.warn(
    `${plaintext.length} payment credential(s) predate encryption and are still stored in plain text. ` +
      'Run `npm run encrypt-credentials` in the backend, or re-save them in Settings.'
  );
}
